package pe.upc.simutalk.enums;

public enum IntegrityFlagType {
    /** The answer reads as generated by an AI assistant rather than by the candidate. */
    AI_GENERATED_CONTENT,
    /** What the candidate declared does not hold up (e.g. certifications the issuer rejected). */
    CV_INCONSISTENCY
}
